services:
  postgres:
    container_name: foodb-postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
